# Generated by Django 4.2.6 on 2023-10-22 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gym',
            name='trainings',
        ),
    ]
