# Generated by Django 4.2.6 on 2023-10-21 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gyms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('email', models.CharField(max_length=255, verbose_name='Почта')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_price', models.IntegerField(verbose_name='Цена тренировки')),
                ('gym_income', models.IntegerField(verbose_name='Доход зала')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases_customer', to='customers.customer', verbose_name='Покупатель')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases_training', to='gyms.training', verbose_name='Тренировка')),
            ],
            options={
                'verbose_name': 'Покупка',
                'verbose_name_plural': 'Покупки',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='purchases',
            field=models.ManyToManyField(related_name='customers_purchase', to='customers.purchase', verbose_name='Покупки'),
        ),
    ]
